version: '3.9'
services:
  app:
    image: gotodo
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - ./:/go/src/app
    ports:
      - "18000:80"
